# Generated by Django 3.2.2 on 2021-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
